LinkLuaModifier("modifier_pvp_damage_layers", "modifiers/modifier_pvp_damage_layers.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_spawn_healing", "modifiers/modifier_spawn_healing.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_aghanim_crystal_activator", "modifiers/modifier_aghanim_crystal_activator.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_custom", "modifiers/modifier_damage_reduction_custom.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_new_game_plus_thinker", "modifiers/modifier_new_game_plus_thinker.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_garbage_collector_fix", "modifiers/modifier_garbage_collector_fix.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creep_antilag_phased", "modifiers/modifier_creep_antilag.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_evil_citadel", "modifiers/modifier_evil_citadel.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_limited_lives", "modifiers/modifier_limited_lives.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_dummy_target", "modifiers/modifier_dummy_target.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gold_bank", "modifiers/modifier_gold_bank.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_outpost_capture", "modifiers/modifier_outpost_capture.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_timmy", "modifiers/modifier_timmy.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_chicken", "modifiers/modifier_chicken.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_aghanim_portal", "modifiers/modifier_aghanim_portal.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_scaling_damage_reduction", "modifiers/modifier_scaling_damage_reduction.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_new_game_plus_magical_resistance", "modifiers/modifier_new_game_plus_magical_resistance.lua", LUA_MODIFIER_MOTION_NONE)

-- Buffs and boons --
LinkLuaModifier("modifier_player_difficulty_buff_gold_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_gold_50.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_heal_on_kill_25", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_heal_on_kill_25.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_damage_reduction_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_damage_reduction_50.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_armor_50", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_armor_50.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_damage_25", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_damage_25.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_bounty_rune_200", "modifiers/modes/buffs/easy/modifier_player_difficulty_buff_bounty_rune_200.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_player_difficulty_buff_bounty_rune_50", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_bounty_rune_50.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_gold_10", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_gold_10.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_difficulty_buff_heal_on_kill_10", "modifiers/modes/buffs/normal/modifier_player_difficulty_buff_heal_on_kill_10.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_apocalypse_corpse_explosion", "modifiers/apocalypse_modifiers/corpse_explosion.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_increased_speed", "modifiers/apocalypse_modifiers/increased_speed.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_attack_range", "modifiers/apocalypse_modifiers/attack_range.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_armor", "modifiers/apocalypse_modifiers/armor.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_resistance", "modifiers/apocalypse_modifiers/magic_resistance.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_evasion", "modifiers/apocalypse_modifiers/evasion.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_attacks", "modifiers/apocalypse_modifiers/magic_attacks.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_mana_burn", "modifiers/apocalypse_modifiers/mana_burn.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_life_blood", "modifiers/apocalypse_modifiers/life_blood.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_rushing", "modifiers/apocalypse_modifiers/rushing.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_health_deny", "modifiers/apocalypse_modifiers/health_deny.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_magic_shield", "modifiers/apocalypse_modifiers/magic_shield.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_mana_void", "modifiers/apocalypse_modifiers/mana_void.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_apocalypse_reanimation", "modifiers/apocalypse_modifiers/reanimation.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_player_buffs_enemy_explosion", "modifiers/player_buffs/modifier_player_buffs_enemy_explosion.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_adrenaline", "modifiers/player_buffs/modifier_player_buffs_adrenaline.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_critical_strike", "modifiers/player_buffs/modifier_player_buffs_critical_strike.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_attack_sacrifice", "modifiers/player_buffs/modifier_player_buffs_attack_sacrifice.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_spell_sacrifice", "modifiers/player_buffs/modifier_player_buffs_spell_sacrifice.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_sanguine_clarity", "modifiers/player_buffs/modifier_player_buffs_sanguine_clarity.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_omniscent_blessing", "modifiers/player_buffs/modifier_player_buffs_omniscent_blessing.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_vulnerable", "modifiers/player_buffs/modifier_player_buffs_vulnerable.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_glasscannon", "modifiers/player_buffs/modifier_player_buffs_glasscannon.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_status_boost", "modifiers/player_buffs/modifier_player_buffs_status_boost.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_hard_exterior", "modifiers/player_buffs/modifier_player_buffs_hard_exterior.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_blood_pool", "modifiers/player_buffs/modifier_player_buffs_blood_pool.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_vitality_curse", "modifiers/player_buffs/modifier_player_buffs_vitality_curse.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_mana_curse", "modifiers/player_buffs/modifier_player_buffs_mana_curse.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_drunken_brawler", "modifiers/player_buffs/modifier_player_buffs_drunken_brawler.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_buffs_bloodthirsty_killer", "modifiers/player_buffs/modifier_player_buffs_bloodthirsty_killer.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_dummy_wearable_hero", "modifiers/modifier_dummy_wearable_hero.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_walking_animation_fix", "modifiers/modifier_walking_animation_fix.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_wave_manager_unit_ai", "modules/wave_manager/WaveManager.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_player", "modules/wave_manager/WaveManager.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_player_attribute_debuff", "modules/wave_manager/WaveManager.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wave_manager_fow_revealer", "modules/wave_manager/WaveManager.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_max_movement_speed", "modifiers/modifier_max_movement_speed.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_season_shock", "modifiers/seasons/modifier_season_shock.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_frenzy", "modifiers/seasons/modifier_season_frenzy.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_firestorm", "modifiers/seasons/modifier_season_firestorm.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_death", "modifiers/seasons/modifier_season_death.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_season_lightning", "modifiers/seasons/modifier_season_lightning.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_intellect_talent_1", "abilities/talents/intellect/xp_intellect_talent_1.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_2", "abilities/talents/intellect/xp_intellect_talent_2.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_3", "abilities/talents/intellect/xp_intellect_talent_3.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_4", "abilities/talents/intellect/xp_intellect_talent_4.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_7", "abilities/talents/intellect/xp_intellect_talent_7.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_8", "abilities/talents/intellect/xp_intellect_talent_8.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_9", "abilities/talents/intellect/xp_intellect_talent_9.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_10", "abilities/talents/intellect/xp_intellect_talent_10.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_12", "abilities/talents/intellect/xp_intellect_talent_12.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_13", "abilities/talents/intellect/xp_intellect_talent_13.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_14", "abilities/talents/intellect/xp_intellect_talent_14.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_15", "abilities/talents/intellect/xp_intellect_talent_15.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_17", "abilities/talents/intellect/xp_intellect_talent_17.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_18", "abilities/talents/intellect/xp_intellect_talent_18.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_20", "abilities/talents/intellect/xp_intellect_talent_20.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_intellect_talent_23", "abilities/talents/intellect/xp_intellect_talent_23.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_strength_talent_1", "abilities/talents/strength/xp_strength_talent_1.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_2", "abilities/talents/strength/xp_strength_talent_2.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_3", "abilities/talents/strength/xp_strength_talent_3.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_4", "abilities/talents/strength/xp_strength_talent_4.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_5", "abilities/talents/strength/xp_strength_talent_5.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_7", "abilities/talents/strength/xp_strength_talent_7.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_8", "abilities/talents/strength/xp_strength_talent_8.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_9", "abilities/talents/strength/xp_strength_talent_9.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_10", "abilities/talents/strength/xp_strength_talent_10.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_11", "abilities/talents/strength/xp_strength_talent_11.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_12", "abilities/talents/strength/xp_strength_talent_12.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_13", "abilities/talents/strength/xp_strength_talent_13.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_14", "abilities/talents/strength/xp_strength_talent_14.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_15", "abilities/talents/strength/xp_strength_talent_15.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_17", "abilities/talents/strength/xp_strength_talent_17.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_18", "abilities/talents/strength/xp_strength_talent_18.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_20", "abilities/talents/strength/xp_strength_talent_20.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_strength_talent_23", "abilities/talents/strength/xp_strength_talent_23.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_agility_talent_1", "abilities/talents/agility/xp_agility_talent_1.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_2", "abilities/talents/agility/xp_agility_talent_2.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_3", "abilities/talents/agility/xp_agility_talent_3.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_4", "abilities/talents/agility/xp_agility_talent_4.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_5", "abilities/talents/agility/xp_agility_talent_5.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_6", "abilities/talents/agility/xp_agility_talent_6.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_7", "abilities/talents/agility/xp_agility_talent_7.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_8", "abilities/talents/agility/xp_agility_talent_8.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_9", "abilities/talents/agility/xp_agility_talent_9.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_10", "abilities/talents/agility/xp_agility_talent_10.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_11", "abilities/talents/agility/xp_agility_talent_11.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_12", "abilities/talents/agility/xp_agility_talent_12.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_13", "abilities/talents/agility/xp_agility_talent_13.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_14", "abilities/talents/agility/xp_agility_talent_14.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_15", "abilities/talents/agility/xp_agility_talent_15.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_16", "abilities/talents/agility/xp_agility_talent_16.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_17", "abilities/talents/agility/xp_agility_talent_17.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_18", "abilities/talents/agility/xp_agility_talent_18.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_20", "abilities/talents/agility/xp_agility_talent_20.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_agility_talent_23", "abilities/talents/agility/xp_agility_talent_23.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_all_talent_1", "abilities/talents/all/xp_all_talent_1.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_2", "abilities/talents/all/xp_all_talent_2.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_3", "abilities/talents/all/xp_all_talent_3.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_4", "abilities/talents/all/xp_all_talent_4.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_5", "abilities/talents/all/xp_all_talent_5.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_6", "abilities/talents/all/xp_all_talent_6.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_7", "abilities/talents/all/xp_all_talent_7.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_8", "abilities/talents/all/xp_all_talent_8.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_9", "abilities/talents/all/xp_all_talent_9.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_10", "abilities/talents/all/xp_all_talent_10.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_11", "abilities/talents/all/xp_all_talent_11.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_12", "abilities/talents/all/xp_all_talent_12.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_13", "abilities/talents/all/xp_all_talent_13.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_14", "abilities/talents/all/xp_all_talent_14.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_15", "abilities/talents/all/xp_all_talent_15.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_16", "abilities/talents/all/xp_all_talent_16.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_17", "abilities/talents/all/xp_all_talent_17.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_18", "abilities/talents/all/xp_all_talent_18.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_20", "abilities/talents/all/xp_all_talent_20.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_xp_all_talent_23", "abilities/talents/all/xp_all_talent_23.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_xp_manager_player", "modules/xp_manager/XpManager.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_auto_pickup", "modifiers/modifier_auto_pickup.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_twin_gate_custom", "modifiers/modifier_twin_gate_custom.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_aghanim_tower", "modifiers/modifier_aghanim_tower.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_uber_bosses_portal", "modifiers/modifier_uber_bosses_portal.lua", LUA_MODIFIER_MOTION_NONE)

-- Runes --
LinkLuaModifier("modifier_item_socket_rune_legendary_drow_ranger_multishot", "modifiers/runes/heroes/drow_ranger/modifier_item_socket_rune_legendary_drow_ranger_multishot.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_drow_ranger_marksmanship", "modifiers/runes/heroes/drow_ranger/modifier_item_socket_rune_legendary_drow_ranger_marksmanship.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_medusa_split_shot", "modifiers/runes/heroes/medusa/modifier_item_socket_rune_legendary_medusa_split_shot.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_faceless_void_time_lock", "modifiers/runes/heroes/faceless_void/modifier_item_socket_rune_legendary_faceless_void_time_lock.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_faceless_void_chronosphere", "modifiers/runes/heroes/faceless_void/modifier_item_socket_rune_legendary_faceless_void_chronosphere.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_lina_light_strike_array", "modifiers/runes/heroes/lina/modifier_item_socket_rune_legendary_lina_light_strike_array.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_tidehunter_anchor_smash", "modifiers/runes/heroes/tidehunter/modifier_item_socket_rune_legendary_tidehunter_anchor_smash.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_axe_counter_helix", "modifiers/runes/heroes/axe/modifier_item_socket_rune_legendary_axe_counter_helix.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_axe_culling_blade", "modifiers/runes/heroes/axe/modifier_item_socket_rune_legendary_axe_culling_blade.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_luna_moon_beam", "modifiers/runes/heroes/luna/modifier_item_socket_rune_legendary_luna_moon_beam.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_item_socket_rune_legendary_lone_druid_bear", "modifiers/runes/heroes/lone_druid/modifier_item_socket_rune_legendary_lone_druid_bear.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_hero_tanya", "heroes/hero_tanya/modifier_hero_tanya.lua", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_boss_arc_warden_ai", "heroes/bosses/arc_warden/ai.lua", LUA_MODIFIER_MOTION_NONE)